plugin.name=OpenSageTV Vibe TMDB Metadata Service
plugin.identifier=opensagetv-vibe-tmdb
plugin.implementation=org.opensagetv.vibe.tmdb.plugin.OpenSageTVVibeTmdbPlugin
plugin.version=0.1.1
plugin.sagetv.minimum=9.0.0
plugin.java.minimum=1.8.0
plugin.author=OpenSageTV Vibe
plugin.webpage=https://github.com/opensagetv-vibe/opensagetv-vibe-tmdb
