plugin.name=OpenSageTV Vibe TMDB Metadata Service
plugin.identifier=opensagetv-vibe-tmdb
plugin.implementation=org.opensagetv.vibe.tmdb.plugin.OpenSageTVVibeTmdbPlugin
plugin.version=0.1.0-dev
plugin.sagetv.minimum=9.0.0
